ls:
  '*':
    .dir: kebab-case
    .js: kebab-case
    .ts: kebab-case
    .tsx: kebab-case
    .d.ts: kebab-case
    .spec.ts: kebab-case
    .spec.tsx: kebab-case

ignore:
  - .git
  - .github
  - .husky
  - node_modules
  - .pnpm-store
